#!/bin/sh

echo "------ HOOK START - BUILD -------"
#printenv

#set -x

DAVMAIL_REV="2652"
if [ "$DOCKER_TAG" = "trunk" ]
 then
  DAVMAIL_REV="HEAD"
 fi

docker build --build-arg DAVMAIL_REV=$DAVMAIL_REV -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
